infos_from_json = File.read("db/bantamweight.json")
JSON.parse(infos_from_json).each do |t|
    Fighter.create!(nickname: t,
        name: t,
        ranking: t,
        record: t,
        age: t,
        height: t,
        weight: t,
        octagon_debut: t,
        reach: t, 
        leg_reach: t, 
        StrAcc: t,
        GrpAcc: t,
        SLpM: t, 
        SAbpm: t,
        TDAvg: t,
        SubAvg: t,
        StrDef: t, 
        TDDef: t, 
        Knockdown_ratio: t,
        AvgFt: t,
        SSbPS: t,
        SSbPC: t,
        SSbPG: t,
        WbWKO: t,
        WbWDec: t,
        WbWSub: t,
        SSbTH: t,
        SSbTB: t,
        SSbTL: t,
        Img: t)
end
